# Generated by Django 3.2.18 on 2023-05-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='portifolio.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_project/'),
        ),
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_update/'),
        ),
        migrations.AddField(
            model_name='update',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_update/'),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='portifolio.project'),
        ),
    ]
