# Generated by Django 3.2.18 on 2023-05-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_auto_20230506_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates_project', to='portifolio.update'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='programming_language',
            field=models.CharField(max_length=155),
        ),
    ]
