# Generated by Django 3.2.18 on 2023-05-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_auto_20230508_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='project',
            name='programming_language',
        ),
        migrations.RemoveField(
            model_name='category',
            name='projects',
        ),
        migrations.AddField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_categories', to='portifolio.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(related_name='frameworks', to='portifolio.Framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='programming_languages',
            field=models.ManyToManyField(related_name='programming_languages', to='portifolio.ProgrammingLanguage'),
        ),
    ]
