# Generated by Django 3.2.18 on 2023-05-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_auto_20230508_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(related_name='project_categories', to='portifolio.Project'),
        ),
    ]
