# Generated by Django 3.2.18 on 2023-05-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='portifolio.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='frameworks',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_frameworks', to='portifolio.Framework'),
        ),
        migrations.AddField(
            model_name='course',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_languages', to='portifolio.ProgrammingLanguage'),
        ),
    ]
