# Generated by Django 3.2.18 on 2023-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0011_auto_20230512_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='frameworks',
            field=models.ManyToManyField(related_name='course_frameworks', to='portifolio.Framework'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programming_languages',
            field=models.ManyToManyField(related_name='course_languages', to='portifolio.ProgrammingLanguage'),
        ),
    ]
