# Generated by Django 3.2.18 on 2023-05-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0012_auto_20230513_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_language', to='portifolio.programminglanguage'),
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low'), (2, 'Regular'), (3, 'High')], null=True),
        ),
    ]
