# Generated by Django 3.2.18 on 2023-05-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0014_alter_project_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1h to 40h'), (2, '41h to 100h'), (3, '> 100h')], null=True),
        ),
    ]
