# Generated by Django 3.2.18 on 2023-05-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0015_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
