# Generated by Django 3.2.18 on 2023-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0018_alter_course_licence_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course_category', to='portifolio.Category'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='project', to='portifolio.Category'),
        ),
    ]
