# Generated by Django 3.2.18 on 2023-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0021_alter_customer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
