# Generated by Django 3.2.18 on 2023-06-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0022_alter_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_category', to='portifolio.category'),
        ),
    ]
