# Generated by Django 3.2.18 on 2023-06-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0023_framework_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_categories', to='portifolio.Project'),
        ),
    ]
