# Generated by Django 3.2.18 on 2023-06-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0024_alter_category_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='project_categories', to='portifolio.Project'),
        ),
    ]
