# Generated by Django 3.2.18 on 2023-06-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0026_auto_20230608_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='course_frameworks', to='portifolio.Framework'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='course_languages', to='portifolio.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='programming_languages', to='portifolio.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to='portifolio.update'),
        ),
    ]
