# Generated by Django 3.2.18 on 2023-06-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0027_auto_20230608_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='frameworks', to='portifolio.Framework'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to='portifolio.update'),
        ),
    ]
