# Generated by Django 3.2.18 on 2023-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0028_auto_20230608_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complexity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Basic'), (2, 'Regular'), (4, 'High'), (10, 'Professional')], null=True),
        ),
    ]
