# Generated by Django 3.2.18 on 2023-06-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0029_alter_project_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='functions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='possible_upgrades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
