# Generated by Django 3.2.18 on 2023-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0030_auto_20230609_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company_icon',
            field=models.FileField(blank=True, null=True, upload_to='company_icon'),
        ),
    ]
